---
title: "Nicar 2024 - Tipsheets & Recordings"
output: html_document
date:
---

```{r, echo=FALSE, include=FALSE}
library(rjson)
library(tidyverse)
library(dplyr)
library(knitr)
```

```{r, echo=FALSE}
json_data <- fromJSON(file="https://resources.ire.org/meta/nicar-2024-tipsheets-audio.json")

sessions_df <- data.frame(session_title = character(), 
                          speakers = character(), 
                          #description = character(),
                          tipsheets = character(), 
                          audio_recording_link = character(), 
                          stringsAsFactors = FALSE)


for (day in json_data$sessions) {
  for (session in day$data) {
    ## 
    session_title <- session$session_title
    speakers <- session$speakers
    if (session$audio_recording_link != "") {
        audio_recording_link <- paste0("[", "Audio Recording", "](", session$audio_recording_link, ")")
    } else {
      audio_recording_link <- NA
    }
     
    if (length(session$tipsheets) > 0) {
      tipsheet_links <- sapply(session$tipsheets, function(t) paste0("[", t$label, "](", t$url, ")"))
      tipsheets <- paste(tipsheet_links, collapse = ", ")
    } else {
      tipsheets <- NA
    }
    
    # Append this row to the data frame
    sessions_df <- rbind(sessions_df, data.frame(session_title, speakers, audio_recording_link, tipsheets, stringsAsFactors = FALSE))
  }
}
# Convert tipsheets URLs to HTML links for display in datatable
sessions_df$audio_recording_link <- sapply(sessions_df$audio_recording_link, function(x) {
  gsub("\\[(.*?)\\]\\((.*?)\\)", "<a href='\\2'>\\1</a>", x)
}, USE.NAMES = FALSE)

# Convert tipsheets URLs to HTML links for display in datatable
sessions_df$tipsheets <- sapply(sessions_df$tipsheets, function(x) {
  gsub("\\[(.*?)\\]\\((.*?)\\)", "<a href='\\2'>\\1</a>", x)
}, USE.NAMES = FALSE)

```

```{r, echo=FALSE, include=FALSE}
write_csv(sessions_df, "session_df.csv")
```

```{r, echo=FALSE, include=TRUE}
DT::datatable(sessions_df, options = list(pageLength = 20), escape = FALSE)
```



